### ISSUE TITLE
Provide a CMake Package Configuration File

### ISSUE THREAD

**Issue by stubb** [unittest-cpp/unittest-cpp#99] opened 2016-02-21 16:15 UTC
It would be great if a CMake package configuration file would be installed/provided altogether with the lib itself. So everyone running an own CMake project could include/find unittest++ easily with the Cmake command find_package().
See https://cmake.org/Wiki/CMake/Tutorials/Packaging for details.

**Comment by pjohnmeyer** [comment] 2016-02-24 04:56
Agreed. This is a duplicate of #89, though, so I'm closing it.

**Comment by pjohnmeyer** [comment] 2016-02-24 06:31
Ah, disregard previous comment -- related but not the same.

**Closed** 2016-04-20 03:11 UTC
Labels: enhancement

**Comment by stubb** [comment] 2016-04-20 15:28
Thanks!
